name: Release

on:
  push:
    tags:
      - '*'
jobs:
  release:
    env:
      IMAGE_NAME: github-traffic-arm64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      run: |
        git clone -b ${GITHUB_REF#refs/tags/} --single-branch https://github.com/grafana/github-traffic.git
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login GHCR
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get docker image version
      id: get_version
      run: echo version=${GITHUB_REF#refs/tags/} >> $GITHUB_OUTPUT
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: ./github-traffic
        file: ./github-traffic/Dockerfile
        platforms: linux/arm64
        provenance: false
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.version }}
